### ISSUE TITLE
What is Salt parameter when generate a new identity ?

### ISSUE THREAD

**Issue by beljk** [mgp25/WhatsAPINet#14]
@mgp25  I passed a value to Salt parameter but I don't know what is Salt ??
is it a password or what??
public static string GenerateIdentity(string phoneNumber, string salt)
        {
            return (phoneNumber + salt).Reverse().ToSHAString();
        }

**Comment by mgp25** [comment]
look at the function name, generateIdentity, so what it generates?

**Comment by beljk** [comment]
yes I know what it generates but I want to know what is salt ??? what do you mean by salt ?
