### ISSUE TITLE
SendSync() Limit 

### ISSUE THREAD

**Issue by diyaa-hamza** [mgp25/WhatsAPINet#15]
Hi,

I have tried to use SendSync() method to check if the user has WhatsApp or not. And I got the result successfully, BUT if I wanna check another number I did not get result after PollMessages() no thing happened. And after hold for 30 minutes I got the result.

Any information about that?

Tnx

**Comment by mgp25** [comment]
There is a backoff time we need to respect, WhatsApp did this in order to avoid massive requests.

Regards
